#!/usr/bin/env python3
"""Writes crates/yagni-commander-core/src/icons/table.rs from nvim-web-devicons.

Only glyphs in the Unicode Private Use Areas are kept: the others are ordinary
characters that the bundled Nerd Font does not contain. Rerun after changing TAG;
the font test in icons.rs checks every glyph against the font.
"""
import io
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

TAG = "v0.100"
URL = f"https://github.com/nvim-tree/nvim-web-devicons/archive/refs/tags/{TAG}.tar.gz"
OUT = Path(__file__).resolve().parent.parent / "crates/yagni-commander-core/src/icons/table.rs"


def private_use(c: str) -> bool:
    cp = ord(c)
    return 0xE000 <= cp <= 0xF8FF or cp >= 0xF0000


def table(src: str, name: str) -> list[tuple[str, str]]:
    body = re.search(rf"local {name} = {{\n(.*?)\n}}\n", src, re.S).group(1)
    entries = re.findall(r'^  \["([^"]+)"\] = \{\n    icon = "([^"]*)",', body, re.M)
    declared = len(re.findall(r'^  \["', body, re.M))
    assert len(entries) == declared, f"{name}: parsed {len(entries)} of {declared}"
    kept, dropped = [], []
    for key, icon in entries:
        assert len(icon) == 1, f"{name}: {key} has a multi-character icon"
        (kept if private_use(icon) else dropped).append((key, icon))
    for key, icon in dropped:
        print(f"{name}: dropped {key} (U+{ord(icon):04X} is not a Nerd Font glyph)", file=sys.stderr)
    keys = [k for k, _ in kept]
    assert len(keys) == len(set(keys)), f"{name}: duplicate keys"
    return sorted(kept)


def rust(name: str, entries: list[tuple[str, str]]) -> str:
    lines = [f"pub(crate) static {name}: &[(&str, char)] = &["]
    lines += [f'    ("{k}", \'\\u{{{ord(i):x}}}\'),' for k, i in entries]
    lines.append("];")
    return "\n".join(lines)


def main() -> None:
    data = urllib.request.urlopen(URL).read()
    with tarfile.open(fileobj=io.BytesIO(data)) as tar:
        member = next(m for m in tar.getmembers() if m.name.endswith("/icons-default.lua"))
        src = tar.extractfile(member).read().decode("utf-8")
    names = table(src, "icons_by_filename")
    extensions = table(src, "icons_by_file_extension")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"//! Generated by `scripts/gen-icons.py` from nvim-web-devicons {TAG}\n"
        "//! (MIT, https://github.com/nvim-tree/nvim-web-devicons). Do not edit.\n\n"
        + rust("FILE_NAMES", names) + "\n\n" + rust("EXTENSIONS", extensions) + "\n"
    )
    print(f"{OUT}: {len(names)} file names, {len(extensions)} extensions")


if __name__ == "__main__":
    main()
